---
# Variables used by the Geerlingguy Postgresql role

postgresql_databases:
  - name: '{{ pulp_database_config["default"]["NAME"] }}'
    owner: '{{ pulp_database_config["default"]["NAME"] }}'

postgresql_users:
  - name: '{{ pulp_database_config["default"]["USER"] }}'
    password: '{{ pulp_database_config["default"]["PASSWORD"] }}'
    role_attr_flags: CREATEDB
