---
- name: restart postgresql with service
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted
    enabled: yes
  become: true

- name: restart postgresql with systemd
  systemd:
    name: "{{ postgresql_service_name }}"
    state: restarted
    enabled: yes
  when: ansible_service_mgr == 'systemd'
  become: true
